"""empty message

Revision ID: 63e250cb71ca
Revises: bd2759c610b9
Create Date: 2023-04-09 19:36:45.117872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63e250cb71ca'
down_revision = 'bd2759c610b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('release_date', sa.Date(), nullable=False))
        batch_op.drop_column('relase_date')

    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.LargeBinary(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.LargeBinary(),
               type_=mysql.TEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               nullable=True)

    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relase_date', sa.DATE(), nullable=False))
        batch_op.drop_column('release_date')

    # ### end Alembic commands ###
